version: '3.8'

services:
  server:
    build:
      context: ./server
    ports:
      - "4000:4000"
    volumes:
      - ./server:/usr/src/app


  client:
    build:
      context: ./client
    ports:
      - "3000:80"
    volumes:
      - ./client:/usr/src/app
    depends_on:
      - server

